package ExceptionHandling;

public class TryCatch {

	public static void main(String[] args) {

		int a = 0;
		int b = 17;

		/*
		 * try { double div = b / a; } finally {
		 * System.out.println("shubham handsome hai"); }
		 */

		/*
		 * try{ double d = b / a; } catch(ArithmeticException e){
		 * System.out.println("shubham cute hai"); }
		 */

		/*
		 * try{ double D = b / a; } catch (RuntimeException e){ } catch
		 * (ArithmeticException a){ }
		 */

		/* double Div = b/a; */

		/*try {
			double A = b / a;
			String s = "vijay";

		} catch (StringIndexOutOfBoundsException | NullPointerException e) {
			System.out.println("shubham");
		} catch (IndexOutOfBoundsException e) {
		}*/
	}
}